# Generated by Django 4.0.3 on 2022-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0002_candidate_jobdescription_alter_candidate_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('companyaddress', models.CharField(max_length=250)),
                ('jobdescription', models.TextField(max_length=500)),
                ('qualification', models.CharField(max_length=250)),
                ('resposibilties', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('companywebsite', models.CharField(max_length=250)),
                ('companyemail', models.CharField(max_length=250)),
                ('companycontact', models.CharField(max_length=20)),
                ('salarypackage', models.CharField(max_length=250)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(upload_to='app/img/Company'),
        ),
    ]
