# Generated by Django 4.0.3 on 2022-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0005_jobdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDetails',
        ),
    ]
