# Generated by Django 4.0.3 on 2022-04-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0008_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
