# Generated by Django 4.0.3 on 2022-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0009_applylist_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='experience',
            field=models.IntegerField(default=''),
        ),
    ]
