# Generated by Django 4.0.3 on 2022-04-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Jobapp.usermaster'),
            preserve_default=False,
        ),
    ]
