# Generated by Django 4.0.3 on 2022-04-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0014_remove_contact_contact_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Jobapp.usermaster'),
            preserve_default=False,
        ),
    ]
