# Generated by Django 4.0.3 on 2022-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0015_contact_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Subject',
            field=models.TextField(max_length=200),
        ),
    ]
