# Generated by Django 4.0.3 on 2022-04-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0016_alter_contact_message_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact1',
        ),
        migrations.AlterField(
            model_name='contact1',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobapp.candidate'),
        ),
    ]
