# Generated by Django 4.0.3 on 2022-04-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0017_rename_contact_contact1_alter_contact1_contact_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
