# Generated by Django 4.0.3 on 2022-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0018_delete_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactsend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=50)),
                ('Subject', models.TextField(max_length=200)),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
    ]
