# Generated by Django 4.0.3 on 2022-04-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0019_contactsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsend',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Jobapp.usermaster'),
            preserve_default=False,
        ),
    ]
