# Generated by Django 4.0.3 on 2022-04-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0020_contactsend_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsend',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contactsend',
            name='contact_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Jobapp.candidate'),
            preserve_default=False,
        ),
    ]
