# Generated by Django 4.0.3 on 2022-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0021_remove_contactsend_user_id_contactsend_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsend',
            old_name='contact_id',
            new_name='user_id',
        ),
    ]
