# Generated by Django 4.0.3 on 2022-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0022_rename_contact_id_contactsend_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsend',
            name='Contact',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
