# Generated by Django 4.0.3 on 2022-05-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0024_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
