# Generated by Django 4.0.3 on 2022-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0025_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Middlename', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Dob', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=50)),
                ('Marital_status', models.CharField(default='', max_length=150)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Website', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(max_length=150)),
                ('Graduation', models.CharField(max_length=150)),
                ('University_college', models.CharField(max_length=150)),
                ('Degree_certification', models.CharField(max_length=150)),
                ('Course_title', models.CharField(max_length=150)),
                ('Additional_information', models.CharField(max_length=150)),
                ('Company_name', models.CharField(max_length=150)),
                ('Job_position', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=150)),
                ('Date_From', models.CharField(max_length=50)),
                ('Date_To', models.CharField(max_length=50)),
                ('Skills', models.CharField(max_length=150)),
                ('Skill_proficiency', models.CharField(max_length=150)),
            ],
        ),
    ]
