# Generated by Django 4.0.3 on 2022-06-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0026_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
